# This makes travis use the thin image which boots faster
language: generic

# sudo:required is needed for docker use
sudo: required

services:
- docker

install:
- docker build -t particle . 

script:
- docker run -v $(pwd):/workdir particle

