language: cpp
compiler: gcc
before_install:
    - sudo add-apt-repository ppa:codegear/ppa -y
    - sudo apt-get update -y
install: sudo apt-get install premake4 libXxf86vm-dev -y 
script: 
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - cmake -DBUILD_SHARED_LIBS=ON
    - make
    - sudo make install
    - cd ..
    - ./build.sh
