language: cpp
compiler: clang 
before_install:
    - sudo add-apt-repository ppa:codegear/release -y 
    - sudo apt-get update -q
install: sudo apt-get install -y premake4 libXxf86vm-dev 
script: 
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - cmake -DBUILD_SHARED_LIBS=ON
    - make
    - sudo make install
    - cd ..
    - CC=clang
    - CXX=clang++
    - ./build.sh
